version: 1 # must be `1`
patchUpdated:
  generators:
  - command: /sbin/apk add yarn python3 npm && pip3 install pipenv && pipenv run pip install constructs && yarn global add cdk8s-cli && cdk8s import && cdk8s synth && cat dist/*
  patchFile: flux-patch.yaml
